### PR TITLE
Pinging System Implemented in C++/CLI

### PR DESCRIPTION
**Pull request by Jester565**
The pinging system has now been made compatible with C#.
Major Changes:
-PingManager added to Comms
-Sleep time of send and recv threads in Comms have been reduced to 16 ms instead of 1000 ms (you can increase this, but if you do you will also have to increase variables in Pinger)

Possible Issues:
-PingManager will not suspend when Comms::Stop or Comms::Pause is called.  This is to prevent mutexes from being locked and never unlocked when the thread is suspended.  I can think of a workaround to this but I think it is a low priority issue given these methods have not been implemented in the C++ version of the project.

### CODE REVIEW

**Comment by CheezBoiger** [comment]
Looks mighty tasty    ' '3

**Comment by CheezBoiger** [comment]
ima add this in.

**Comment by Jester565** [comment]
Haha thanks!  C++/CLI was quite interesting...

**Comment by CheezBoiger** [comment]
Glad you got hands on experience! Not many people know how to translate from one language to another lulz.

**Pull request merged**
