### PR TITLE
Cmake now puts the libxbee3 dynamic library into the tests.

### PR DESCRIPTION
**Pull request by Jester565**
This was tested on Windows and Ubuntu.  However, I could not test it on Mac.  Perhaps we could get someone to test this on Mac before accepting the pull request?

### CODE REVIEW

**Comment by CheezBoiger** [comment]
Linux and OSX are easy to link to your program. For some reason, windows doesn't handle it easy, as you have to do a little work to link it manually. This is really good though 👍

**Comment by MichaelWallace30** [comment]
Its fine will test it after

**Comment by Jester565** [comment]
Didn't OSX have a .dylib file that they have to copy over?

**Comment by MichaelWallace30** [comment]
Yes it did the code looks fine.

**Comment by CheezBoiger** [comment]
enjoy some rewarding 8bitness: https://www.youtube.com/watch?v=cjFgXr19LFI  	 (^・ω・^ )

**Comment by MichaelWallace30** [comment]
They will get things done in no time with a reward system like that.

**Comment by CheezBoiger** [comment]
wise words from a wise mang...       c( - w -  c  )

**Comment by Jester565** [comment]
Haha awesome!  I appreciate the music!

**Pull request merged**
