### PR TITLE
Thread safety to autoqueue. Change UdpLink::map to UdpLink::clients.

### PR DESCRIPTION
**Pull request by Jester565**
Sorry for making this a pull request.  I don't really know another way of going about this.

### CODE REVIEW

**Comment by MichaelWallace30** [comment]
I merged the wrong way on Friday. I dont know what this is, but it looks like its messed up.

**Comment by MichaelWallace30** [comment]
The revert failed and  Mario forced a push that fixed  it. I see the revert in the commits.

**Comment by Jester565** [comment]
So the ping repository is messed up even though it has the revert?

**Comment by MichaelWallace30** [comment]
The revert is the issue.

**Comment by MichaelWallace30** [comment]
It didnt revert recent changes you and Mario made.

**Comment by Jester565** [comment]
Ok I'll revert my pull request when I can

**Comment by MichaelWallace30** [comment]
I think you need to do a force push or pull.  I would wait for Mario to wake up.

**Comment by Jester565** [comment]
Save us Mario!

**Comment by Jester565** [comment]
Maybe we can just delete the entire branch and create a new one from master?

**Comment by MichaelWallace30** [comment]
Yeah man you can do what ever.

**Comment by Jester565** [comment]
Worst comes to worst we trash this branch, but I think I fixed it.  Maybe.
I would never do this with the master branch though.

**Pull request merged**
